
import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  useColorScheme,
  Platform,
} from 'react-native';
import { Stack, router } from 'expo-router';
import { colors } from '@/styles/commonStyles';
import { IconSymbol } from '@/components/IconSymbol';
import NoiseTexture from '@/components/NoiseTexture';
import Modal from '@/components/ui/Modal';
import * as Haptics from 'expo-haptics';
import * as Sharing from 'expo-sharing';
import * as Clipboard from 'expo-clipboard';
import {
  getFavorites,
  removeFavorite,
  clearAllFavorites,
  type FavoriteExcuse,
} from '@/utils/storage';

export default function FavoritesScreen() {
  const colorScheme = useColorScheme();
  const isDark = colorScheme === 'dark';
  
  const [favorites, setFavorites] = useState<FavoriteExcuse[]>([]);
  const [loading, setLoading] = useState(true);
  const [deleteModal, setDeleteModal] = useState({ visible: false, id: '', excuse: '' });
  const [clearAllModal, setClearAllModal] = useState(false);
  const [successModal, setSuccessModal] = useState({ visible: false, message: '' });
  const [errorModal, setErrorModal] = useState({ visible: false, message: '' });
  
  useEffect(() => {
    loadFavorites();
  }, []);
  
  const loadFavorites = async () => {
    console.log('Loading favorites');
    setLoading(true);
    try {
      const favs = await getFavorites();
      setFavorites(favs);
      console.log('Favorites loaded:', favs.length);
    } catch (error) {
      console.error('Failed to load favorites:', error);
      setErrorModal({
        visible: true,
        message: 'Failed to load favorites. Please try again.',
      });
    } finally {
      setLoading(false);
    }
  };
  
  const handleDelete = async (id: string) => {
    console.log('Deleting favorite:', id);
    
    if (Platform.OS !== 'web') {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    }
    
    const success = await removeFavorite(id);
    
    if (success) {
      setFavorites(prev => prev.filter(fav => fav.id !== id));
      setSuccessModal({
        visible: true,
        message: 'Excuse deleted! 🗑️',
      });
      
      setTimeout(() => {
        setSuccessModal({ visible: false, message: '' });
      }, 2000);
    } else {
      setErrorModal({
        visible: true,
        message: 'Failed to delete excuse. Please try again.',
      });
    }
    
    setDeleteModal({ visible: false, id: '', excuse: '' });
  };
  
  const handleClearAll = async () => {
    console.log('Clearing all favorites');
    
    if (Platform.OS !== 'web') {
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Warning);
    }
    
    const success = await clearAllFavorites();
    
    if (success) {
      setFavorites([]);
      setSuccessModal({
        visible: true,
        message: 'All favorites cleared! 🧹',
      });
      
      setTimeout(() => {
        setSuccessModal({ visible: false, message: '' });
      }, 2000);
    } else {
      setErrorModal({
        visible: true,
        message: 'Failed to clear favorites. Please try again.',
      });
    }
    
    setClearAllModal(false);
  };
  
  const handleShare = async (excuse: string) => {
    console.log('Sharing favorite excuse');
    
    if (Platform.OS !== 'web') {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    }
    
    const shareText = `${excuse} - Generated by Excuse Generator 3000`;
    
    try {
      if (Platform.OS === 'web') {
        // Web Share API
        if (navigator.share) {
          await navigator.share({
            title: 'Excuse Generator 3000',
            text: shareText,
          });
        } else {
          await navigator.clipboard.writeText(shareText);
          setSuccessModal({
            visible: true,
            message: 'Excuse copied to clipboard!',
          });
          
          setTimeout(() => {
            setSuccessModal({ visible: false, message: '' });
          }, 2000);
        }
      } else {
        // Mobile native share
        const isAvailable = await Sharing.isAvailableAsync();
        
        if (isAvailable) {
          await Sharing.shareAsync('data:text/plain,' + encodeURIComponent(shareText));
        } else {
          await Clipboard.setStringAsync(shareText);
          setSuccessModal({
            visible: true,
            message: 'Excuse copied to clipboard!',
          });
          
          setTimeout(() => {
            setSuccessModal({ visible: false, message: '' });
          }, 2000);
        }
      }
    } catch (error: any) {
      console.error('Failed to share:', error);
      
      // If user cancelled, don't show error
      if (error.message?.includes('cancel') || error.name === 'AbortError') {
        console.log('User cancelled share');
        return;
      }
      
      // Fallback to clipboard
      try {
        if (Platform.OS === 'web') {
          await navigator.clipboard.writeText(shareText);
        } else {
          await Clipboard.setStringAsync(shareText);
        }
        
        setSuccessModal({
          visible: true,
          message: 'Excuse copied to clipboard!',
        });
        
        setTimeout(() => {
          setSuccessModal({ visible: false, message: '' });
        }, 2000);
      } catch (clipboardError) {
        console.error('Failed to copy to clipboard:', clipboardError);
      }
    }
  };
  
  const handleCopy = async (excuse: string) => {
    console.log('Copying excuse to clipboard');
    
    if (Platform.OS !== 'web') {
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    }
    
    try {
      if (Platform.OS === 'web') {
        await navigator.clipboard.writeText(excuse);
      } else {
        await Clipboard.setStringAsync(excuse);
      }
      
      setSuccessModal({
        visible: true,
        message: 'Excuse copied! 📋',
      });
      
      setTimeout(() => {
        setSuccessModal({ visible: false, message: '' });
      }, 2000);
    } catch (error) {
      console.error('Failed to copy to clipboard:', error);
      setErrorModal({
        visible: true,
        message: 'Failed to copy excuse. Please try again.',
      });
    }
  };
  
  const formatTimestamp = (timestamp: number): string => {
    const now = Date.now();
    const diff = now - timestamp;
    
    const seconds = Math.floor(diff / 1000);
    const minutes = Math.floor(seconds / 60);
    const hours = Math.floor(minutes / 60);
    const days = Math.floor(hours / 24);
    
    if (seconds < 60) {
      return 'just now';
    }
    if (minutes < 60) {
      const minuteText = minutes === 1 ? 'minute' : 'minutes';
      return `${minutes} ${minuteText} ago`;
    }
    if (hours < 24) {
      const hourText = hours === 1 ? 'hour' : 'hours';
      return `${hours} ${hourText} ago`;
    }
    if (days === 1) {
      return 'yesterday';
    }
    if (days < 7) {
      return `${days} days ago`;
    }
    
    const date = new Date(timestamp);
    const monthText = date.toLocaleDateString('en-US', { month: 'short' });
    const dayText = date.getDate();
    return `${monthText} ${dayText}`;
  };
  
  const bgColor = isDark ? colors.backgroundDark : colors.background;
  const textColor = isDark ? colors.textDark : colors.text;
  const textSecondaryColor = isDark ? colors.textSecondaryDark : colors.textSecondary;
  const cardColor = isDark ? colors.cardDark : colors.card;
  
  return (
    <>
      <Stack.Screen
        options={{
          headerShown: true,
          title: 'MY FAVORITES ❤️',
          headerStyle: {
            backgroundColor: bgColor,
          },
          headerTintColor: colors.hotPink,
          headerTitleStyle: {
            fontWeight: 'bold',
            fontSize: 18,
          },
          headerBackTitle: 'Back',
        }}
      />
      <View style={[styles.container, { backgroundColor: bgColor }]}>
        {isDark && <NoiseTexture opacity={0.04} />}
        
        {loading ? (
          <View style={styles.centerContent}>
            <Text style={[styles.loadingText, { color: textColor }]}>
              Loading favorites...
            </Text>
          </View>
        ) : favorites.length === 0 ? (
          <View style={styles.centerContent}>
            <Text style={styles.emptyIcon}>
              ❤️
            </Text>
            <Text style={[styles.emptyTitle, { color: textColor }]}>
              No excuses saved yet! 💚
            </Text>
            <Text style={[styles.emptySubtitle, { color: textSecondaryColor }]}>
              Tap the ❤️ on any excuse to save it for later
            </Text>
          </View>
        ) : (
          <ScrollView
            style={styles.scrollView}
            contentContainerStyle={styles.scrollContent}
          >
            {favorites.map((fav, index) => {
              const timeAgo = formatTimestamp(fav.timestamp);
              
              return (
                <View key={fav.id} style={[styles.favoriteCard, { backgroundColor: colors.slimeGreen }]}>
                  <Text style={styles.excuseText}>
                    {fav.excuse}
                  </Text>
                  
                  <View style={styles.tagsContainer}>
                    <View style={[styles.tag, { backgroundColor: cardColor }]}>
                      <Text style={[styles.tagText, { color: textColor }]}>
                        {fav.situation}
                      </Text>
                    </View>
                    <View style={[styles.tag, { backgroundColor: cardColor }]}>
                      <Text style={[styles.tagText, { color: textColor }]}>
                        {fav.tone}
                      </Text>
                    </View>
                    <View style={[styles.tag, { backgroundColor: cardColor }]}>
                      <Text style={[styles.tagText, { color: textColor }]}>
                        {fav.length}
                      </Text>
                    </View>
                  </View>
                  
                  <Text style={[styles.timestamp, { color: textSecondaryColor }]}>
                    {timeAgo}
                  </Text>
                  
                  <View style={styles.actionButtons}>
                    <TouchableOpacity
                      onPress={() => handleShare(fav.excuse)}
                      style={[styles.actionButton, { backgroundColor: colors.electricOrange }]}
                    >
                      <IconSymbol
                        ios_icon_name="square.and.arrow.up"
                        android_material_icon_name="share"
                        size={18}
                        color={colors.text}
                      />
                      <Text style={styles.actionButtonText}>
                        SHARE
                      </Text>
                    </TouchableOpacity>
                    
                    <TouchableOpacity
                      onPress={() => handleCopy(fav.excuse)}
                      style={[styles.actionButton, { backgroundColor: colors.accent }]}
                    >
                      <IconSymbol
                        ios_icon_name="doc.on.doc"
                        android_material_icon_name="content-copy"
                        size={18}
                        color={colors.text}
                      />
                      <Text style={styles.actionButtonText}>
                        COPY
                      </Text>
                    </TouchableOpacity>
                    
                    <TouchableOpacity
                      onPress={() => {
                        setDeleteModal({
                          visible: true,
                          id: fav.id,
                          excuse: fav.excuse,
                        });
                      }}
                      style={[styles.actionButton, { backgroundColor: '#FF3B30' }]}
                    >
                      <IconSymbol
                        ios_icon_name="trash"
                        android_material_icon_name="delete"
                        size={18}
                        color={colors.text}
                      />
                      <Text style={styles.actionButtonText}>
                        DELETE
                      </Text>
                    </TouchableOpacity>
                  </View>
                </View>
              );
            })}
            
            {favorites.length > 0 && (
              <TouchableOpacity
                onPress={() => setClearAllModal(true)}
                style={[styles.clearAllButton, { backgroundColor: '#FF3B30' }]}
              >
                <IconSymbol
                  ios_icon_name="trash.fill"
                  android_material_icon_name="delete"
                  size={20}
                  color={colors.text}
                />
                <Text style={styles.clearAllButtonText}>
                  CLEAR ALL FAVORITES
                </Text>
              </TouchableOpacity>
            )}
            
            <View style={{ height: 40 }} />
          </ScrollView>
        )}
        
        {/* Delete Confirmation Modal */}
        <Modal
          visible={deleteModal.visible}
          onClose={() => setDeleteModal({ visible: false, id: '', excuse: '' })}
          title="Delete this excuse?"
          message="This action cannot be undone."
          type="warning"
          confirmText="Delete"
          cancelText="Cancel"
          onConfirm={() => handleDelete(deleteModal.id)}
        />
        
        {/* Clear All Confirmation Modal */}
        <Modal
          visible={clearAllModal}
          onClose={() => setClearAllModal(false)}
          title="Delete all saved excuses?"
          message="This will permanently delete all your favorites. This action cannot be undone."
          type="warning"
          confirmText="Delete All"
          cancelText="Cancel"
          onConfirm={handleClearAll}
        />
        
        {/* Success Modal */}
        <Modal
          visible={successModal.visible}
          onClose={() => setSuccessModal({ visible: false, message: '' })}
          title="Success!"
          message={successModal.message}
          type="success"
          confirmText="OK"
        />
        
        {/* Error Modal */}
        <Modal
          visible={errorModal.visible}
          onClose={() => setErrorModal({ visible: false, message: '' })}
          title="Oops!"
          message={errorModal.message}
          type="error"
          confirmText="OK"
        />
      </View>
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  centerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  loadingText: {
    fontSize: 16,
    fontWeight: '600',
  },
  emptyIcon: {
    fontSize: 80,
    marginBottom: 20,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 16,
    textAlign: 'center',
    lineHeight: 24,
  },
  scrollView: {
    flex: 1,
    zIndex: 2,
  },
  scrollContent: {
    padding: 20,
  },
  favoriteCard: {
    padding: 20,
    borderRadius: 20,
    marginBottom: 20,
    borderWidth: 4,
    borderColor: colors.text,
    shadowColor: colors.text,
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  excuseText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    lineHeight: 24,
    marginBottom: 15,
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  tag: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.text,
  },
  tagText: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  timestamp: {
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 15,
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 3,
    borderColor: colors.text,
    gap: 6,
  },
  actionButtonText: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.text,
  },
  clearAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    marginTop: 10,
    borderWidth: 4,
    borderColor: colors.text,
    shadowColor: colors.text,
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
    gap: 10,
  },
  clearAllButtonText: {
    fontSize: 16,
    fontWeight: '900',
    color: colors.text,
    letterSpacing: 1,
  },
});
